### ISSUE TITLE
equally contribution

### ISSUE THREAD

**Issue by ZacHu-ZYH** [xulabs/projects#6]
Hi，
I am submitting a paper to miccai and want to ask for information about how to add "authorA and B equally contribution", could I include this information directly in the paper or when I submit it in the system?
I would be grateful if you could answer me

**Comment by xulabs** [comment]
I don't remember. You can take a look at recent miccai papers and see how they do this.

**Comment by ZacHu-ZYH** [comment]
anyway, thank u！




            
            
                
                    
                            
                                
                            
                            
                                1254678934
                            
                    
                        
                            
                                    邮箱：1254678934@qq.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


On 02/22/2020 20:13, xulabs wrote: Closed #6.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/xulabs/projects/issues/6?email_source=notifications\u0026email_token=AKJKO2T4LKJ7XDJS7RL62KDREEJFZA5CNFSM4KZN3XV2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOW2GOSPY#event-3062688063",
"url": "https://github.com/xulabs/projects/issues/6?email_source=notifications\u0026email_token=AKJKO2T4LKJ7XDJS7RL62KDREEJFZA5CNFSM4KZN3XV2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOW2GOSPY#event-3062688063",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
